logging:
  path: logs/v1.0.0
spring:
  cloud:
    inetutils:
      ignored-interfaces: #忽略docker0网卡以及 veth开头的网卡
        - docker0
        - veth.*
    consul:
      host: 127.0.0.1
      port: 8500
      enabled: true
      discovery:
        enabled: true
        prefer-ip-address: true
        service-name: bbjh-gateway
        tags:
          - java
          - gateway
        instance-id: instance-${spring.cloud.client.ip-address}-${spring.application.name}-${server.port}